name: CICD

on:
  push:
    branches: [ master ]
    workflow_dispatch:
  schedule:
    - cron: '* */6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: check out repo
        uses: actions/checkout@v2

      - name: login dockerhub
        uses: docker/login-action@v1
        with:
          username: nand0p
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: docker buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: nand0p/covid19:latest
          build_args:
            DATE: $(date)
            REVISION: ${{ github.sha }}

      - name: echo digest
        run: echo ${{ steps.docker_build.outputs.digest }}
